name: Conda packages (Ubuntu Lab1)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.11
      uses: actions/setup-java@v1
      with:
        java-version: 1.11  
    - name: Cache gradle
      uses: actions/cache@v2
      with:
        path: ~/.gradle/caches
        key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
        restore-keys: |
          ${{ runner.os }}-gradle-  
    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        miniconda-version: "latest"
    - name: Verify conda version
      shell: bash -l {0}
      run: conda --version
    - name: Create conda env
      shell: bash -l {0}
      run: |
        conda create -y --name beakerx_all_lab python=3.7.5
        conda activate beakerx_all_lab
        conda install -y -c conda-forge openjdk=11.0.1
        conda install -y -c conda-forge jupyterlab=2
    - name: Install beakerx_all
      shell: bash -l {0}
      run: |
        conda activate beakerx_all_lab
        conda install -y -c beakerx beakerx_all
        beakerx install
        beakerx_tabledisplay install
        conda list

